// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobby.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLobby = `-- name: GetLobby :one
SELECT id, host_player, lobby_name, start_at, player_count, gamemode, ingame_id FROM lobby WHERE id = $1
`

func (q *Queries) GetLobby(ctx context.Context, id uuid.UUID) (Lobby, error) {
	row := q.db.QueryRow(ctx, getLobby, id)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartAt,
		&i.PlayerCount,
		&i.Gamemode,
		&i.IngameID,
	)
	return i, err
}

const insertLobby = `-- name: InsertLobby :one
INSERT INTO lobby(host_player, lobby_name, start_at, player_count, gamemode) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id, host_player, lobby_name, start_at, player_count, gamemode, ingame_id
`

type InsertLobbyParams struct {
	HostPlayer  uuid.UUID `json:"host_player"`
	LobbyName   string    `json:"lobby_name"`
	StartAt     time.Time `json:"start_at"`
	PlayerCount int32     `json:"player_count"`
	Gamemode    Gamemode  `json:"gamemode"`
}

func (q *Queries) InsertLobby(ctx context.Context, arg InsertLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, insertLobby,
		arg.HostPlayer,
		arg.LobbyName,
		arg.StartAt,
		arg.PlayerCount,
		arg.Gamemode,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartAt,
		&i.PlayerCount,
		&i.Gamemode,
		&i.IngameID,
	)
	return i, err
}

const updateGameId = `-- name: UpdateGameId :exec
UPDATE lobby SET ingame_id = $1 WHERE id = $2
`

type UpdateGameIdParams struct {
	IngameID pgtype.Text `json:"ingame_id"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateGameId(ctx context.Context, arg UpdateGameIdParams) error {
	_, err := q.db.Exec(ctx, updateGameId, arg.IngameID, arg.ID)
	return err
}
