// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package database

import (
	"context"
)

const getAllPlayer = `-- name: GetAllPlayer :many
SELECT id, name FROM Player
`

func (q *Queries) GetAllPlayer(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, getAllPlayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlayer = `-- name: InsertPlayer :exec
INSERT INTO Player(name) 
VALUES ($1)
`

func (q *Queries) InsertPlayer(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertPlayer, name)
	return err
}
