// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package database

import (
	"context"
)

const getAllPlayer = `-- name: GetAllPlayer :many
SELECT id, player_name FROM player
`

func (q *Queries) GetAllPlayer(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, getAllPlayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.PlayerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlayer = `-- name: InsertPlayer :one
INSERT INTO player(player_name) 
VALUES ($1)
RETURNING id, player_name
`

func (q *Queries) InsertPlayer(ctx context.Context, playerName string) (Player, error) {
	row := q.db.QueryRow(ctx, insertPlayer, playerName)
	var i Player
	err := row.Scan(&i.ID, &i.PlayerName)
	return i, err
}
