// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package database

import (
	"context"
)

const getCountry = `-- name: GetCountry :one
SELECT id FROM countries WHERE country_tag = $1
`

func (q *Queries) GetCountry(ctx context.Context, countryTag string) (int16, error) {
	row := q.db.QueryRow(ctx, getCountry, countryTag)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const listCountries = `-- name: ListCountries :many
SELECT country_tag FROM countries
`

func (q *Queries) ListCountries(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var country_tag string
		if err := rows.Scan(&country_tag); err != nil {
			return nil, err
		}
		items = append(items, country_tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
