// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package database

import (
	"context"
)

const getCountries = `-- name: GetCountries :many
SELECT
    country_tag,
    country_name
FROM countries
`

type GetCountriesRow struct {
	CountryTag  string `json:"country_tag"`
	CountryName string `json:"country_name"`
}

func (q *Queries) GetCountries(ctx context.Context) ([]GetCountriesRow, error) {
	rows, err := q.db.Query(ctx, getCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountriesRow
	for rows.Next() {
		var i GetCountriesRow
		if err := rows.Scan(&i.CountryTag, &i.CountryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryID = `-- name: GetCountryID :one
SELECT id FROM countries
WHERE country_tag = $1
`

func (q *Queries) GetCountryID(ctx context.Context, countryTag string) (int16, error) {
	row := q.db.QueryRow(ctx, getCountryID, countryTag)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const getCountryTag = `-- name: GetCountryTag :one
SELECT country_tag FROM countries
WHERE id = $1
`

func (q *Queries) GetCountryTag(ctx context.Context, id int16) (string, error) {
	row := q.db.QueryRow(ctx, getCountryTag, id)
	var country_tag string
	err := row.Scan(&country_tag)
	return country_tag, err
}
