// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobby.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addLobbyCountry = `-- name: AddLobbyCountry :exec
INSERT INTO lobby_countries (lobby_id, country_id, max_slots)
VALUES (
    $1,
    (
        SELECT id FROM countries
        WHERE country_tag = $2
    ),
    $3
)
`

type AddLobbyCountryParams struct {
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
	MaxSlots   int32  `json:"max_slots"`
}

func (q *Queries) AddLobbyCountry(ctx context.Context, arg AddLobbyCountryParams) error {
	_, err := q.db.Exec(ctx, addLobbyCountry, arg.LobbyID, arg.CountryTag, arg.MaxSlots)
	return err
}

const countCountryOccupants = `-- name: CountCountryOccupants :one
SELECT COUNT(*) FROM player_lobby
WHERE
    lobby_id = $1 AND country_id
    = (
        SELECT id FROM countries
        WHERE country_tag = $2
    )
    AND player_id != $3
`

type CountCountryOccupantsParams struct {
	LobbyID    int64     `json:"lobby_id"`
	CountryTag string    `json:"country_tag"`
	PlayerID   uuid.UUID `json:"player_id"`
}

func (q *Queries) CountCountryOccupants(ctx context.Context, arg CountCountryOccupantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCountryOccupants, arg.LobbyID, arg.CountryTag, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decrementPlayerCount = `-- name: DecrementPlayerCount :one
UPDATE lobby SET player_count = player_count - 1
WHERE id = $1 RETURNING player_count
`

func (q *Queries) DecrementPlayerCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, decrementPlayerCount, id)
	var player_count int32
	err := row.Scan(&player_count)
	return player_count, err
}

const getLobbyCountries = `-- name: GetLobbyCountries :many
SELECT
    countries.country_tag,
    lobby_countries.max_slots
FROM lobby_countries
JOIN countries ON lobby_countries.country_id = countries.id
WHERE lobby_countries.lobby_id = $1
`

type GetLobbyCountriesRow struct {
	CountryTag string `json:"country_tag"`
	MaxSlots   int32  `json:"max_slots"`
}

func (q *Queries) GetLobbyCountries(ctx context.Context, lobbyID int64) ([]GetLobbyCountriesRow, error) {
	rows, err := q.db.Query(ctx, getLobbyCountries, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLobbyCountriesRow
	for rows.Next() {
		var i GetLobbyCountriesRow
		if err := rows.Scan(&i.CountryTag, &i.MaxSlots); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLobbyInfo = `-- name: GetLobbyInfo :one
SELECT id, host_player, lobby_name, starts_at, player_count, gamemode, ingame_id, description
FROM lobby
WHERE id = $1
`

func (q *Queries) GetLobbyInfo(ctx context.Context, id int64) (Lobby, error) {
	row := q.db.QueryRow(ctx, getLobbyInfo, id)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartsAt,
		&i.PlayerCount,
		&i.Gamemode,
		&i.IngameID,
		&i.Description,
	)
	return i, err
}

const getLobbyPlayers = `-- name: GetLobbyPlayers :many
SELECT
    player.player_name,
    player_lobby.lobby_id,
    countries.country_tag
FROM player_lobby
JOIN countries ON player_lobby.country_id = countries.id
JOIN player ON player_lobby.player_id = player.id
WHERE player_lobby.lobby_id = $1
`

type GetLobbyPlayersRow struct {
	PlayerName string `json:"player_name"`
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
}

func (q *Queries) GetLobbyPlayers(ctx context.Context, lobbyID int64) ([]GetLobbyPlayersRow, error) {
	rows, err := q.db.Query(ctx, getLobbyPlayers, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLobbyPlayersRow
	for rows.Next() {
		var i GetLobbyPlayersRow
		if err := rows.Scan(&i.PlayerName, &i.LobbyID, &i.CountryTag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPlayerCount = `-- name: IncrementPlayerCount :one
UPDATE lobby
SET player_count = player_count + 1
WHERE
    id = $1
    AND player_count <= 32
RETURNING player_count
`

func (q *Queries) IncrementPlayerCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPlayerCount, id)
	var player_count int32
	err := row.Scan(&player_count)
	return player_count, err
}

const insertLobby = `-- name: InsertLobby :one
INSERT INTO lobby (
    host_player,
    lobby_name,
    starts_at,
    gamemode,
    description
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, host_player, lobby_name, starts_at, player_count, gamemode, ingame_id, description
`

type InsertLobbyParams struct {
	HostPlayer  uuid.UUID `json:"host_player"`
	LobbyName   string    `json:"lobby_name"`
	StartsAt    time.Time `json:"starts_at"`
	Gamemode    Gamemode  `json:"gamemode"`
	Description string    `json:"description"`
}

func (q *Queries) InsertLobby(ctx context.Context, arg InsertLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, insertLobby,
		arg.HostPlayer,
		arg.LobbyName,
		arg.StartsAt,
		arg.Gamemode,
		arg.Description,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartsAt,
		&i.PlayerCount,
		&i.Gamemode,
		&i.IngameID,
		&i.Description,
	)
	return i, err
}

const lockLobbyCountrySlot = `-- name: LockLobbyCountrySlot :one
SELECT max_slots
FROM lobby_countries
WHERE
    lobby_id = $1 AND country_id = (
        SELECT c.id FROM countries AS c
        WHERE c.country_tag = $2
    )
FOR UPDATE
`

type LockLobbyCountrySlotParams struct {
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
}

func (q *Queries) LockLobbyCountrySlot(ctx context.Context, arg LockLobbyCountrySlotParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockLobbyCountrySlot, arg.LobbyID, arg.CountryTag)
	var max_slots int32
	err := row.Scan(&max_slots)
	return max_slots, err
}

const openLobbies = `-- name: OpenLobbies :one
SELECT COUNT(*) FROM lobby
WHERE starts_at <= NOW()
`

func (q *Queries) OpenLobbies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, openLobbies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPlayerInLobby = `-- name: SearchPlayerInLobby :one
SELECT country_id FROM player_lobby
WHERE lobby_id = $1 AND player_id = $2
`

type SearchPlayerInLobbyParams struct {
	LobbyID  int64     `json:"lobby_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) SearchPlayerInLobby(ctx context.Context, arg SearchPlayerInLobbyParams) (int16, error) {
	row := q.db.QueryRow(ctx, searchPlayerInLobby, arg.LobbyID, arg.PlayerID)
	var country_id int16
	err := row.Scan(&country_id)
	return country_id, err
}

const unassignPlayer = `-- name: UnassignPlayer :exec
DELETE FROM player_lobby
WHERE lobby_id = $1 AND player_id = $2
`

type UnassignPlayerParams struct {
	LobbyID  int64     `json:"lobby_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) UnassignPlayer(ctx context.Context, arg UnassignPlayerParams) error {
	_, err := q.db.Exec(ctx, unassignPlayer, arg.LobbyID, arg.PlayerID)
	return err
}

const updateGameId = `-- name: UpdateGameId :exec
UPDATE lobby SET ingame_id = $1
WHERE id = $2
`

type UpdateGameIdParams struct {
	IngameID pgtype.Text `json:"ingame_id"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateGameId(ctx context.Context, arg UpdateGameIdParams) error {
	_, err := q.db.Exec(ctx, updateGameId, arg.IngameID, arg.ID)
	return err
}

const upsertPlayerLobby = `-- name: UpsertPlayerLobby :one
INSERT INTO player_lobby (player_id, lobby_id, country_id)
SELECT
    $1,
    $2,
    id
FROM countries
WHERE country_tag = $3
ON CONFLICT (lobby_id, player_id)
DO UPDATE SET country_id = excluded.country_id
RETURNING player_id, lobby_id, country_id, joined_at
`

type UpsertPlayerLobbyParams struct {
	PlayerID   uuid.UUID `json:"player_id"`
	LobbyID    int64     `json:"lobby_id"`
	CountryTag string    `json:"country_tag"`
}

func (q *Queries) UpsertPlayerLobby(ctx context.Context, arg UpsertPlayerLobbyParams) (PlayerLobby, error) {
	row := q.db.QueryRow(ctx, upsertPlayerLobby, arg.PlayerID, arg.LobbyID, arg.CountryTag)
	var i PlayerLobby
	err := row.Scan(
		&i.PlayerID,
		&i.LobbyID,
		&i.CountryID,
		&i.JoinedAt,
	)
	return i, err
}
