// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobby.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCountryOccupants = `-- name: CountCountryOccupants :one
SELECT COUNT(*) FROM player_lobby
WHERE
    lobby_id = $1 AND country_id
    = (
        SELECT id FROM countries
        WHERE country_tag = $2
    )
    AND player_id != $3
`

type CountCountryOccupantsParams struct {
	LobbyID    int64     `json:"lobby_id"`
	CountryTag string    `json:"country_tag"`
	PlayerID   uuid.UUID `json:"player_id"`
}

func (q *Queries) CountCountryOccupants(ctx context.Context, arg CountCountryOccupantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCountryOccupants, arg.LobbyID, arg.CountryTag, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLobbyCountry = `-- name: DeleteLobbyCountry :one
DELETE FROM lobby_countries
WHERE lobby_id = $1 AND country_id = (
    SELECT id FROM countries
    WHERE country_tag = $2
) RETURNING lobby_id, country_id, max_slots
`

type DeleteLobbyCountryParams struct {
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
}

func (q *Queries) DeleteLobbyCountry(ctx context.Context, arg DeleteLobbyCountryParams) (LobbyCountry, error) {
	row := q.db.QueryRow(ctx, deleteLobbyCountry, arg.LobbyID, arg.CountryTag)
	var i LobbyCountry
	err := row.Scan(&i.LobbyID, &i.CountryID, &i.MaxSlots)
	return i, err
}

const deleteLobbyPlayer = `-- name: DeleteLobbyPlayer :one
DELETE FROM player_lobby
WHERE lobby_id = $1 AND player_id = $2 RETURNING player_id, lobby_id, country_id, note, joined_at
`

type DeleteLobbyPlayerParams struct {
	LobbyID  int64     `json:"lobby_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) DeleteLobbyPlayer(ctx context.Context, arg DeleteLobbyPlayerParams) (PlayerLobby, error) {
	row := q.db.QueryRow(ctx, deleteLobbyPlayer, arg.LobbyID, arg.PlayerID)
	var i PlayerLobby
	err := row.Scan(
		&i.PlayerID,
		&i.LobbyID,
		&i.CountryID,
		&i.Note,
		&i.JoinedAt,
	)
	return i, err
}

const getLobbyCountries = `-- name: GetLobbyCountries :many
SELECT
    countries.country_tag,
    lobby_countries.max_slots
FROM lobby_countries
JOIN countries ON lobby_countries.country_id = countries.id
WHERE lobby_countries.lobby_id = $1
`

type GetLobbyCountriesRow struct {
	CountryTag string `json:"country_tag"`
	MaxSlots   int16  `json:"max_slots"`
}

func (q *Queries) GetLobbyCountries(ctx context.Context, lobbyID int64) ([]GetLobbyCountriesRow, error) {
	rows, err := q.db.Query(ctx, getLobbyCountries, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLobbyCountriesRow
	for rows.Next() {
		var i GetLobbyCountriesRow
		if err := rows.Scan(&i.CountryTag, &i.MaxSlots); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLobbyFromHostID = `-- name: GetLobbyFromHostID :one
SELECT l.id FROM lobby AS l
WHERE l.host_player = $1 AND l.id = $2
`

type GetLobbyFromHostIDParams struct {
	HostPlayer uuid.UUID `json:"host_player"`
	ID         int64     `json:"id"`
}

func (q *Queries) GetLobbyFromHostID(ctx context.Context, arg GetLobbyFromHostIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLobbyFromHostID, arg.HostPlayer, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLobbyInfo = `-- name: GetLobbyInfo :one
SELECT id, host_player, lobby_name, starts_at, gamemode, ingame_id, description
FROM lobby
WHERE id = $1
`

func (q *Queries) GetLobbyInfo(ctx context.Context, id int64) (Lobby, error) {
	row := q.db.QueryRow(ctx, getLobbyInfo, id)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartsAt,
		&i.Gamemode,
		&i.IngameID,
		&i.Description,
	)
	return i, err
}

const getLobbyPlayers = `-- name: GetLobbyPlayers :many
SELECT
    player.player_name,
    player_lobby.lobby_id,
    countries.country_tag
FROM player_lobby
JOIN countries ON player_lobby.country_id = countries.id
JOIN player ON player_lobby.player_id = player.id
WHERE player_lobby.lobby_id = $1
`

type GetLobbyPlayersRow struct {
	PlayerName string `json:"player_name"`
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
}

func (q *Queries) GetLobbyPlayers(ctx context.Context, lobbyID int64) ([]GetLobbyPlayersRow, error) {
	rows, err := q.db.Query(ctx, getLobbyPlayers, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLobbyPlayersRow
	for rows.Next() {
		var i GetLobbyPlayersRow
		if err := rows.Scan(&i.PlayerName, &i.LobbyID, &i.CountryTag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLobby = `-- name: InsertLobby :one
INSERT INTO lobby (
    host_player,
    lobby_name,
    starts_at,
    gamemode,
    description
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, host_player, lobby_name, starts_at, gamemode, ingame_id, description
`

type InsertLobbyParams struct {
	HostPlayer  uuid.UUID `json:"host_player"`
	LobbyName   string    `json:"lobby_name"`
	StartsAt    time.Time `json:"starts_at"`
	Gamemode    Gamemode  `json:"gamemode"`
	Description string    `json:"description"`
}

func (q *Queries) InsertLobby(ctx context.Context, arg InsertLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, insertLobby,
		arg.HostPlayer,
		arg.LobbyName,
		arg.StartsAt,
		arg.Gamemode,
		arg.Description,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartsAt,
		&i.Gamemode,
		&i.IngameID,
		&i.Description,
	)
	return i, err
}

const lockLobbyCountrySlot = `-- name: LockLobbyCountrySlot :one
SELECT lc.max_slots
FROM lobby_countries AS lc
WHERE
    lobby_id = $1 AND country_id = (
        SELECT c.id FROM countries AS c
        WHERE c.country_tag = $2
    )
FOR UPDATE OF lc
`

type LockLobbyCountrySlotParams struct {
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
}

func (q *Queries) LockLobbyCountrySlot(ctx context.Context, arg LockLobbyCountrySlotParams) (int16, error) {
	row := q.db.QueryRow(ctx, lockLobbyCountrySlot, arg.LobbyID, arg.CountryTag)
	var max_slots int16
	err := row.Scan(&max_slots)
	return max_slots, err
}

const openLobbies = `-- name: OpenLobbies :one
SELECT COUNT(*) FROM lobby
WHERE starts_at <= NOW()
`

func (q *Queries) OpenLobbies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, openLobbies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPlayerInLobby = `-- name: SearchPlayerInLobby :one
SELECT country_id FROM player_lobby
WHERE lobby_id = $1 AND player_id = $2
`

type SearchPlayerInLobbyParams struct {
	LobbyID  int64     `json:"lobby_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) SearchPlayerInLobby(ctx context.Context, arg SearchPlayerInLobbyParams) (int16, error) {
	row := q.db.QueryRow(ctx, searchPlayerInLobby, arg.LobbyID, arg.PlayerID)
	var country_id int16
	err := row.Scan(&country_id)
	return country_id, err
}

const updateLobby = `-- name: UpdateLobby :one
UPDATE lobby
SET
    -- we use COALESCE takes the first, non-null value from left to right
    -- sqlc.nargs() specifies nullable arguments
    lobby_name = COALESCE($1, lobby_name),
    description = COALESCE($2, description),
    starts_at = COALESCE($3, starts_at),
    ingame_id = COALESCE($4, ingame_id)
WHERE id = $5
RETURNING id, host_player, lobby_name, starts_at, gamemode, ingame_id, description
`

type UpdateLobbyParams struct {
	LobbyName   pgtype.Text        `json:"lobby_name"`
	Description pgtype.Text        `json:"description"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	IngameID    pgtype.Text        `json:"ingame_id"`
	LobbyID     int64              `json:"lobby_id"`
}

func (q *Queries) UpdateLobby(ctx context.Context, arg UpdateLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, updateLobby,
		arg.LobbyName,
		arg.Description,
		arg.StartsAt,
		arg.IngameID,
		arg.LobbyID,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.HostPlayer,
		&i.LobbyName,
		&i.StartsAt,
		&i.Gamemode,
		&i.IngameID,
		&i.Description,
	)
	return i, err
}

const updateLobbyCountry = `-- name: UpdateLobbyCountry :one
UPDATE lobby_countries SET max_slots = $3
WHERE lobby_id = $1 AND country_id = (
    SELECT id FROM countries
    WHERE country_tag = $2
) RETURNING lobby_id, country_id, max_slots
`

type UpdateLobbyCountryParams struct {
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
	MaxSlots   int16  `json:"max_slots"`
}

func (q *Queries) UpdateLobbyCountry(ctx context.Context, arg UpdateLobbyCountryParams) (LobbyCountry, error) {
	row := q.db.QueryRow(ctx, updateLobbyCountry, arg.LobbyID, arg.CountryTag, arg.MaxSlots)
	var i LobbyCountry
	err := row.Scan(&i.LobbyID, &i.CountryID, &i.MaxSlots)
	return i, err
}

const upsertLobbyCountry = `-- name: UpsertLobbyCountry :one
INSERT INTO lobby_countries (lobby_id, country_id, max_slots)
SELECT
    $1,
    id,
    $3
FROM countries
WHERE country_tag = $2
ON CONFLICT (lobby_id, country_id)
DO UPDATE SET max_slots = excluded.max_slots
RETURNING lobby_id, country_id, max_slots
`

type UpsertLobbyCountryParams struct {
	LobbyID    int64  `json:"lobby_id"`
	CountryTag string `json:"country_tag"`
	MaxSlots   int16  `json:"max_slots"`
}

func (q *Queries) UpsertLobbyCountry(ctx context.Context, arg UpsertLobbyCountryParams) (LobbyCountry, error) {
	row := q.db.QueryRow(ctx, upsertLobbyCountry, arg.LobbyID, arg.CountryTag, arg.MaxSlots)
	var i LobbyCountry
	err := row.Scan(&i.LobbyID, &i.CountryID, &i.MaxSlots)
	return i, err
}

const upsertLobbyPlayer = `-- name: UpsertLobbyPlayer :one
INSERT INTO player_lobby (player_id, lobby_id, country_id, note)
SELECT
    $1,
    $2,
    id,
    $4
FROM countries
WHERE country_tag = $3
ON CONFLICT (lobby_id, player_id)
DO UPDATE SET country_id = excluded.country_id, note = excluded.note
RETURNING player_id, lobby_id, country_id, note, joined_at
`

type UpsertLobbyPlayerParams struct {
	PlayerID   uuid.UUID   `json:"player_id"`
	LobbyID    int64       `json:"lobby_id"`
	CountryTag string      `json:"country_tag"`
	Note       pgtype.Text `json:"note"`
}

// when the player is already in the lobby, we just update the tag and note
func (q *Queries) UpsertLobbyPlayer(ctx context.Context, arg UpsertLobbyPlayerParams) (PlayerLobby, error) {
	row := q.db.QueryRow(ctx, upsertLobbyPlayer,
		arg.PlayerID,
		arg.LobbyID,
		arg.CountryTag,
		arg.Note,
	)
	var i PlayerLobby
	err := row.Scan(
		&i.PlayerID,
		&i.LobbyID,
		&i.CountryID,
		&i.Note,
		&i.JoinedAt,
	)
	return i, err
}
