// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllPlayer = `-- name: GetAllPlayer :many
SELECT id, player_name FROM player
`

func (q *Queries) GetAllPlayer(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, getAllPlayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.PlayerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT player_name FROM player
WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var player_name string
	err := row.Scan(&player_name)
	return player_name, err
}

const insertNewPlayer = `-- name: InsertNewPlayer :one
INSERT INTO player (player_name)
VALUES ($1)
RETURNING id, player_name
`

func (q *Queries) InsertNewPlayer(ctx context.Context, playerName string) (Player, error) {
	row := q.db.QueryRow(ctx, insertNewPlayer, playerName)
	var i Player
	err := row.Scan(&i.ID, &i.PlayerName)
	return i, err
}
