set dotenv-load := true

run:
  rmvolume()
  docker compose up --build

dblogin:
  # we could alternatively expose a port on the pg container to connect to
  docker compose exec db psql -U {{env('POSTGRES_USER')}} -d {{env('POSTGRES_DB')}}

rmvolume:
  docker volume rm ironlobby_pgdata

test-db:
  sqlc generate
  go test ./internal/database

test-server:
  sqlc generate
  go test ./internal/server/
