set dotenv-load := true

run:
    go run ./cmd/*

dblogin:
  # we could alternatively expose a port on the pg container to connect to
  docker compose exec db psql -U {{env('POSTGRES_USER')}} -d {{env('POSTGRES_DB')}}

test-db:
  sqlc generate
  go test ./internal/database

test-server:
  sqlc generate
  go test ./internal/server/
